//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bordspil
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameType
    {
        public GameType()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int gameTypeID { get; set; }
        public string gameTypeName { get; set; }
        public int maxPlayers { get; set; }
        public int minPlayers { get; set; }
        public string gameTypeLink { get; set; }
        public string gameTypeImgUrl { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
    }
}
