//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bordspil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int gameID { get; set; }
        public string gameName { get; set; }
        public bool gameActive { get; set; }
        public bool gamePending { get; set; }
        public Nullable<int> gameType_gameTypeID { get; set; }
        public Nullable<int> gameWinner_UserId { get; set; }
    
        public virtual GameType GameType { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
